Repository opsgenie/terraform-provider-opsgenie, pull requests merged in 2019-11, with the labels that each got.

#36 fixed sweeper tests
  opsgenie/resource_opsgenie_schedule_rotation_test.go
  opsgenie/resource_opsgenie_schedule_test.go
Labels: size/XS

#39 Add link to full list of integration types.
  website/docs/r/api_integration.html.markdown
Labels: documentation, size/XS

#42 Upgraded go-sdk-v2 added owner_team_id to email integrations
  CHANGELOG.md
  go.mod
  go.sum
  opsgenie/resource_opsgenie_email_integration.go
  vendor/github.com/opsgenie/opsgenie-go-sdk-v2/integration/request.go
  vendor/modules.txt
  website/docs/r/email_integration.html.markdown
Labels: dependencies, documentation, size/S

#44 Update docs
  website/docs/r/user.html.markdown
Labels: documentation, size/XS
