Repository opsgenie/terraform-provider-opsgenie, pull requests merged in 2019-09, with the labels that each got.

#9 Fix sweeper tests check if owner resource exist
  opsgenie/resource_opsgenie_schedule_rotation_test.go
  opsgenie/resource_opsgenie_user_contact_test.go
Labels: size/M

#10 Create unique resources
  opsgenie/resource_opsgenie_team_test.go
  opsgenie/resource_opsgenie_user_contact_test.go
Labels: size/XS

#11 Fix non unique test cases on acceptance tests
  opsgenie/resource_opsgenie_email_integration_test.go
  opsgenie/resource_opsgenie_escalation_test.go
  opsgenie/resource_opsgenie_maintenance_test.go
  opsgenie/resource_opsgenie_schedule_rotation_test.go
  opsgenie/util.go
Labels: size/M

#12 remove deprecated tag
  website/docs/index.html.markdown
Labels: documentation, size/XS

#13 edit changelog
  CHANGELOG.md
Labels: size/XS

#14 fix html and links
  website/docs/r/maintenance.html.markdown
  website/opsgenie.erb
Labels: documentation, size/XS

#19 Add heartbeat feature
  CHANGELOG.md
  go.mod
  go.sum
  opsgenie/integration_util.go
  opsgenie/provider.go
  opsgenie/resource_opsgenie_heartbeat.go
  opsgenie/resource_opsgenie_heartbeat_test.go
  opsgenie/resource_opsgenie_schedule.go
  opsgenie/resource_opsgenie_team.go
  vendor/github.com/opsgenie/opsgenie-go-sdk-v2/alert/alert_consts.go
  vendor/github.com/opsgenie/opsgenie-go-sdk-v2/client/client.go
  vendor/github.com/opsgenie/opsgenie-go-sdk-v2/heartbeat/heartbeat.go
  vendor/github.com/opsgenie/opsgenie-go-sdk-v2/heartbeat/request.go
  vendor/github.com/opsgenie/opsgenie-go-sdk-v2/heartbeat/result.go
  vendor/github.com/opsgenie/opsgenie-go-sdk-v2/og/entity.go
  vendor/modules.txt
  website/docs/r/heartbeat.html.markdown
  website/opsgenie.erb
Labels: dependencies, documentation, size/XL

#21 Update docs
  website/docs/index.html.markdown
  website/docs/r/api_integration.html.markdown
  website/docs/r/email_integration.html.markdown
  website/docs/r/team.html.markdown
  website/docs/r/user.html.markdown
  website/docs/r/user_contact.html.markdown
Labels: documentation, size/XS

#20 Update the opsgenie_team docs to refer to id not username
  website/docs/r/team.html.markdown
Labels: documentation, size/XS

#24 Add api key to use generated resources
  CHANGELOG.md
  opsgenie/resource_opsgenie_api_integration.go
  website/docs/r/api_integration.html.markdown
Labels: documentation, size/XS

#25 Introduce datasources and edited resources with docs
  CHANGELOG.md
  go.mod
  go.sum
  opsgenie/data_resource_opsgenie_schedule.go
  opsgenie/data_resource_opsgenie_schedule_test.go
  opsgenie/data_source_opsgenie_escalation.go
  opsgenie/data_source_opsgenie_escalation_test.go
  opsgenie/data_source_opsgenie_heartbeat.go
  opsgenie/data_source_opsgenie_heartbeat_test.go
  opsgenie/data_source_opsgenie_team.go
  opsgenie/data_source_opsgenie_team_test.go
  opsgenie/data_source_opsgenie_user.go
  opsgenie/data_source_opsgenie_user_test.go
  opsgenie/provider.go
  opsgenie/resource_opsgenie_api_integration.go
  opsgenie/resource_opsgenie_email_integration.go
  opsgenie/resource_opsgenie_email_integration_test.go
  opsgenie/resource_opsgenie_escalation.go
  opsgenie/resource_opsgenie_escalation_test.go
  opsgenie/resource_opsgenie_schedule.go
  opsgenie/resource_opsgenie_schedule_rotation.go
  opsgenie/resource_opsgenie_schedule_rotation_test.go
  opsgenie/resource_opsgenie_team.go
  opsgenie/resource_opsgenie_team_test.go
  opsgenie/resource_opsgenie_user_contact_test.go
  opsgenie/util.go
  vendor/github.com/opsgenie/opsgenie-go-sdk-v2/contact/result.go
  vendor/github.com/opsgenie/opsgenie-go-sdk-v2/escalation/result.go
  vendor/github.com/opsgenie/opsgenie-go-sdk-v2/og/entity.go
  vendor/modules.txt
  website/docs/d/escalation.html.markdown
  website/docs/d/heartbeat.html.markdown
  website/docs/d/schedule.html.markdown
  website/docs/d/team.html.markdown
  website/docs/d/user.html.markdown
  website/docs/r/api_integration.html.markdown
  website/docs/r/heartbeat.html.markdown
Labels: dependencies, documentation, size/XXL

#26 Add default value for enabled field
  opsgenie/resource_opsgenie_email_integration.go
Labels: size/XS

#28 update docs
  website/opsgenie.erb
Labels: documentation, size/XS
