Repository opsgenie/terraform-provider-opsgenie, pull requests merged in 2020-07, with the labels that each got.

#119 opsgenie_api_integration: Preserve manually set fields by the user
  opsgenie/resource_opsgenie_api_integration.go
Labels: size/XS

#118 Data source for Service API
  opsgenie/data_source_opsgenie_service.go
  opsgenie/data_source_opsgenie_service_test.go
  opsgenie/provider.go
  website/docs/d/service.html.markdown
  website/opsgenie.erb
Labels: documentation, size/L

#128 New Resource: Alert Policy
  go.mod
  go.sum
  opsgenie/provider.go
  opsgenie/resource_opsgenie_alert_policy.go
  opsgenie/resource_opsgenie_alert_policy_test.go
  vendor/github.com/opsgenie/opsgenie-go-sdk-v2/policy/request.go
  vendor/modules.txt
  website/docs/r/alert_policy.html.markdown
  website/opsgenie.erb
Labels: dependencies, documentation, size/XXL

#125 [TeamRoutingRule] Parse missing NOT field while flattening the criteria
  opsgenie/resource_opsgenie_team_routing_rule.go
  opsgenie/resource_opsgenie_team_routing_rule_test.go
  website/docs/r/team_routing_rule.html.markdown
Labels: documentation, size/S

#129 docs(resources/service): clean up non-existent field
  website/docs/r/service.html.markdown
Labels: documentation, size/XS

#130 Service Incident Rule Resource Addition
  opsgenie/provider.go
  opsgenie/resource_opsgenie_service_incident_rule.go
  opsgenie/resource_opsgenie_service_incident_rule_test.go
  website/docs/r/service_incident_rule.html.markdown
  website/opsgenie.erb
Labels: dependencies, documentation, size/XL

#132 fix tags and temp remove details and actions fields
  opsgenie/resource_opsgenie_alert_policy.go
  opsgenie/resource_opsgenie_alert_policy_test.go
  website/docs/r/alert_policy.html.markdown
Labels: documentation, size/S

#134 Correct resource to data in service docs
  website/docs/d/service.html.markdown
Labels: documentation, size/XS

#135 website update
  CHANGELOG.md
  website/docs/d/service.html.markdown
Labels: documentation, size/XS

#137 Issue 136/Opsgenie team name allow dot character
  opsgenie/resource_opsgenie_team.go
Labels: size/XS

#138 Implementation of integration actions for API/Email
  go.mod
  go.sum
  opsgenie/provider.go
  opsgenie/resource_opsgenie_integration_action.go
  opsgenie/resource_opsgenie_integration_action_test.go
  vendor/github.com/opsgenie/opsgenie-go-sdk-v2/integration/request.go
  vendor/github.com/opsgenie/opsgenie-go-sdk-v2/integration/result.go
  vendor/github.com/opsgenie/opsgenie-go-sdk-v2/og/entity.go
  vendor/modules.txt
  website/docs/r/integration_action.markdown
  website/opsgenie.erb
Labels: dependencies, documentation, size/XXL
