Repository opsgenie/terraform-provider-opsgenie, pull requests merged in 2020-04, with the labels that each got.

#91 Changed update maintenance by state
  go.mod
  go.sum
  opsgenie/resource_opsgenie_maintenance.go
  vendor/github.com/opsgenie/opsgenie-go-sdk-v2/maintenance/maintenance.go
  vendor/github.com/opsgenie/opsgenie-go-sdk-v2/maintenance/request.go
  vendor/github.com/opsgenie/opsgenie-go-sdk-v2/maintenance/result.go
  vendor/modules.txt
Labels: dependencies, size/M

#92 Update CHANGELOG.md
  CHANGELOG.md
Labels: size/XS

#88 Fix opsgenie_schedule_rotation resource import
  opsgenie/resource_opsgenie_schedule_rotation.go
  opsgenie/resource_opsgenie_schedule_rotation_test.go
  opsgenie/resource_opsgenie_team_routing_rule.go
  website/docs/r/schedule_rotation.html.markdown
Labels: documentation, size/M

#93 add missing fields for integrations
  CHANGELOG.md
  opsgenie/resource_opsgenie_api_integration.go
  opsgenie/resource_opsgenie_email_integration.go
Labels: size/XS

#95 Check timerestriction is available because it is not mandatory
  opsgenie/resource_opsgenie_schedule_rotation.go
  opsgenie/resource_opsgenie_schedule_rotation_test.go
Labels: size/XS

#96 Fix Team Routing Rules optional fields
  opsgenie/resource_opsgenie_team_routing_rule.go
  website/docs/r/team_routing_rule.html.markdown
Labels: documentation, size/XS
