Repository opsgenie/terraform-provider-opsgenie, pull requests merged in 2020-03, with the labels that each got.

#74 Add warning if Opsgenie username string containers uppercase characters
  CHANGELOG.md
  opsgenie/resource_opsgenie_user.go
  opsgenie/resource_opsgenie_user_test.go
  website/docs/r/user.html.markdown
Labels: documentation, size/S

#75 Update api_integration.html.markdown
  website/docs/r/api_integration.html.markdown
Labels: documentation, size/XS

#68 Added resource notification_rule
  opsgenie/provider.go
  opsgenie/resource_opsgenie_notification_rule.go
  opsgenie/resource_opsgenie_notification_rule_test.go
  vendor/github.com/hashicorp/terraform-plugin-sdk/helper/structure/expand_json_test.go
  vendor/github.com/hashicorp/terraform-plugin-sdk/helper/structure/flatten_json_test.go
  vendor/github.com/hashicorp/terraform-plugin-sdk/helper/structure/normalize_json_test.go
  vendor/github.com/hashicorp/terraform-plugin-sdk/helper/structure/suppress_json_diff_test.go
  vendor/github.com/opsgenie/opsgenie-go-sdk-v2/notification/notification.go
  vendor/github.com/opsgenie/opsgenie-go-sdk-v2/notification/notification_test.go
  vendor/github.com/opsgenie/opsgenie-go-sdk-v2/notification/request.go
  vendor/github.com/opsgenie/opsgenie-go-sdk-v2/notification/result.go
  website/docs/r/notification_rule.html.markdown
  website/opsgenie.erb
Labels: dependencies, documentation, size/XXL

#78 Revert "Added resource notification_rule (#68)"
  opsgenie/provider.go
  opsgenie/resource_opsgenie_notification_rule.go
  opsgenie/resource_opsgenie_notification_rule_test.go
  vendor/github.com/hashicorp/terraform-plugin-sdk/helper/structure/expand_json_test.go
  vendor/github.com/hashicorp/terraform-plugin-sdk/helper/structure/flatten_json_test.go
  vendor/github.com/hashicorp/terraform-plugin-sdk/helper/structure/normalize_json_test.go
  vendor/github.com/hashicorp/terraform-plugin-sdk/helper/structure/suppress_json_diff_test.go
  vendor/github.com/opsgenie/opsgenie-go-sdk-v2/notification/notification.go
  vendor/github.com/opsgenie/opsgenie-go-sdk-v2/notification/notification_test.go
  vendor/github.com/opsgenie/opsgenie-go-sdk-v2/notification/request.go
  vendor/github.com/opsgenie/opsgenie-go-sdk-v2/notification/result.go
  website/docs/r/notification_rule.html.markdown
  website/opsgenie.erb
Labels: dependencies, documentation, size/XXL

#81 Fix Team Routing Rule resource docs
  website/docs/r/team_routing_rule.html.markdown
Labels: documentation, size/XS

#80 fix docs of opsgenie_schedule data type
  website/docs/d/schedule.html.markdown
Labels: documentation, size/XS

#84 Fix opsgenie_schedule resource documentation
  website/docs/r/schedule.html.markdown
Labels: documentation, size/XS

#85 Fix make command in README example
  README.md
Labels: size/XS

#87 Fix missing enabled attribute while importing opsgenie_schedule
  opsgenie/data_resource_opsgenie_schedule.go
  opsgenie/resource_opsgenie_schedule.go
Labels: size/XS

#79 add optional argument to stop maintaining team members, refs #65
  CHANGELOG.md
  opsgenie/resource_opsgenie_team.go
  opsgenie/resource_opsgenie_team_test.go
  website/docs/r/team.html.markdown
Labels: documentation, size/M

#89 edited version and added fields in changelog
  CHANGELOG.md
  website/docs/r/team.html.markdown
Labels: documentation, size/XS
